CREATE TABLE IF NOT EXISTS job (
  id BIGINT NOT NULL,
  company_id BIGINT NOT NULL,
  title VARCHAR(100) NOT NULL,
  city VARCHAR(50) NOT NULL,
  salary_min INT NOT NULL,
  salary_max INT NOT NULL,
  education_requirement ENUM('HIGH_SCHOOL','JUNIOR_COLLEGE','BACHELOR','MASTER','DOCTOR','OTHER') NULL,
  experience_min_years INT NOT NULL DEFAULT 0,
  description TEXT NOT NULL,
  requirements TEXT NOT NULL,
  skills VARCHAR(1000000) NOT NULL,
  status ENUM('DRAFT','PENDING','APPROVED','REJECTED','CLOSED') NOT NULL DEFAULT 'DRAFT',
  version INT NOT NULL DEFAULT 1,
  review_reason VARCHAR(500) NULL,
  published_at DATETIME(3) NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  CONSTRAINT fk_job_company FOREIGN KEY (company_id) REFERENCES profile(id),
  CONSTRAINT ck_job_salary CHECK (salary_min>=0 AND salary_max>=salary_min AND salary_max<=1000000),
  CONSTRAINT ck_job_experience CHECK (experience_min_years BETWEEN 0 AND 50),
  CONSTRAINT ck_job_flags CHECK (version>=1 AND deleted IN (0,1))
);

CREATE TABLE IF NOT EXISTS resume (
  id BIGINT NOT NULL,
  candidate_id BIGINT NOT NULL,
  version INT NOT NULL DEFAULT 1,
  is_current TINYINT NOT NULL DEFAULT 1,
  deleted TINYINT NOT NULL DEFAULT 0,
  current_candidate_id BIGINT GENERATED ALWAYS AS (CASE WHEN is_current=1 AND deleted=0 THEN candidate_id ELSE NULL END),
  file_name VARCHAR(255) NOT NULL,
  file_path VARCHAR(255) NOT NULL,
  file_size BIGINT NOT NULL,
  parse_status ENUM('PENDING','PROCESSING','SUCCESS','FAILED') NOT NULL DEFAULT 'PENDING',
  confirmation_status ENUM('UNCONFIRMED','CONFIRMED') NOT NULL DEFAULT 'UNCONFIRMED',
  conflict_status ENUM('NONE','PENDING_VERIFY','RESOLVED') NOT NULL DEFAULT 'NONE',
  index_status ENUM('NOT_READY','PENDING','PROCESSING','READY','FAILED','DELETING','DELETED') NOT NULL DEFAULT 'NOT_READY',
  parsed_name VARCHAR(50) NULL,
  parsed_phone VARCHAR(32) NULL,
  parsed_education ENUM('HIGH_SCHOOL','JUNIOR_COLLEGE','BACHELOR','MASTER','DOCTOR','OTHER') NULL,
  parsed_skills VARCHAR(1000000) NULL,
  parsed_work_experience VARCHAR(1000000) NULL,
  parsed_internship_experience VARCHAR(1000000) NULL,
  parsed_project_experience VARCHAR(1000000) NULL,
  parsed_campus_experience VARCHAR(1000000) NULL,
  parsed_certificates VARCHAR(1000000) NULL,
  parsed_summary TEXT NULL,
  extracted_text MEDIUMTEXT NULL,
  extraction_method ENUM('TEXT','OCR','MIXED') NULL,
  page_count INT NULL,
  original_profile VARCHAR(1000000) NOT NULL,
  conflicts VARCHAR(1000000) NULL,
  confirmed_profile VARCHAR(1000000) NULL,
  parse_error VARCHAR(1000) NULL,
  index_error VARCHAR(1000) NULL,
  parse_started_at DATETIME(3) NULL,
  confirmed_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  CONSTRAINT uk_resume_current UNIQUE (current_candidate_id),
  CONSTRAINT fk_resume_candidate FOREIGN KEY (candidate_id) REFERENCES profile(id),
  CONSTRAINT ck_resume_flags CHECK (version>=1 AND is_current IN (0,1) AND deleted IN (0,1)),
  CONSTRAINT ck_resume_size CHECK (file_size>0 AND file_size<=10485760),
  CONSTRAINT ck_resume_confirm CHECK (confirmation_status<>'CONFIRMED' OR (parse_status='SUCCESS' AND confirmed_profile IS NOT NULL AND confirmed_at IS NOT NULL))
);

CREATE TABLE IF NOT EXISTS application (
  id BIGINT NOT NULL,
  candidate_id BIGINT NOT NULL,
  job_id BIGINT NOT NULL,
  resume_id BIGINT NOT NULL,
  resume_version INT NOT NULL,
  job_version INT NOT NULL,
  status ENUM('SUBMITTED','VIEWED','SHORTLISTED','REJECTED','WITHDRAWN') NOT NULL DEFAULT 'SUBMITTED',
  profile_source ENUM('CONFIRMED','AI') NOT NULL DEFAULT 'CONFIRMED',
  resume_snapshot VARCHAR(1000000) NOT NULL,
  job_snapshot VARCHAR(1000000) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  CONSTRAINT uk_application_candidate_job UNIQUE (candidate_id,job_id),
  CONSTRAINT fk_application_candidate FOREIGN KEY (candidate_id) REFERENCES profile(id),
  CONSTRAINT fk_application_job FOREIGN KEY (job_id) REFERENCES job(id),
  CONSTRAINT fk_application_resume FOREIGN KEY (resume_id) REFERENCES resume(id),
  CONSTRAINT ck_application_versions CHECK (resume_version>=1 AND job_version>=1)
);

CREATE TABLE IF NOT EXISTS ai_task (
  id BIGINT NOT NULL,
  creator_id BIGINT NOT NULL,
  type ENUM('MATCH','INTERVIEW','ASSISTANT') NOT NULL,
  status ENUM('PENDING','PROCESSING','SUCCESS','FAILED') NOT NULL DEFAULT 'PENDING',
  application_id BIGINT NULL,
  resume_id BIGINT NOT NULL,
  resume_version INT NOT NULL,
  job_id BIGINT NULL,
  job_version INT NULL,
  question VARCHAR(2000) NULL,
  request_key CHAR(64) NOT NULL,
  active_request_key CHAR(64) GENERATED ALWAYS AS (CASE WHEN status IN ('PENDING','PROCESSING') THEN request_key ELSE NULL END),
  input_snapshot VARCHAR(1000000) NOT NULL,
  result VARCHAR(1000000) NULL,
  error_code INT NULL,
  error_message VARCHAR(1000) NULL,
  started_at DATETIME(3) NULL,
  completed_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  CONSTRAINT uk_ai_active_request UNIQUE (active_request_key),
  CONSTRAINT fk_ai_creator FOREIGN KEY (creator_id) REFERENCES profile(id),
  CONSTRAINT fk_ai_application FOREIGN KEY (application_id) REFERENCES application(id),
  CONSTRAINT fk_ai_resume FOREIGN KEY (resume_id) REFERENCES resume(id),
  CONSTRAINT fk_ai_job FOREIGN KEY (job_id) REFERENCES job(id),
  CONSTRAINT ck_ai_inputs CHECK (resume_version>=1 AND ((type='ASSISTANT' AND question IS NOT NULL AND job_id IS NULL AND job_version IS NULL AND application_id IS NULL) OR (type IN ('MATCH','INTERVIEW') AND job_id IS NOT NULL AND job_version>=1))),
  CONSTRAINT ck_ai_result CHECK ((status='SUCCESS' AND result IS NOT NULL AND completed_at IS NOT NULL) OR (status<>'SUCCESS' AND result IS NULL))
);

CREATE TABLE IF NOT EXISTS resume_job_match (
  id BIGINT NOT NULL,
  resume_id BIGINT NOT NULL,
  resume_version INT NOT NULL,
  job_id BIGINT NOT NULL,
  job_version INT NOT NULL,
  score INT NOT NULL,
  reasons VARCHAR(1000000) NOT NULL,
  gaps VARCHAR(1000000) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  CONSTRAINT uk_match_versions UNIQUE (resume_id,resume_version,job_id,job_version),
  CONSTRAINT fk_match_resume FOREIGN KEY (resume_id) REFERENCES resume(id),
  CONSTRAINT fk_match_job FOREIGN KEY (job_id) REFERENCES job(id),
  CONSTRAINT ck_match_score CHECK (score BETWEEN 0 AND 100 AND resume_version>=1 AND job_version>=1)
);

CREATE TABLE IF NOT EXISTS audit_log (
  id BIGINT NOT NULL,
  operator_id BIGINT NOT NULL,
  target_type ENUM('ACCOUNT','PROFILE','JOB','APPLICATION','RESUME') NOT NULL,
  target_id BIGINT NOT NULL,
  action VARCHAR(50) NOT NULL,
  reason VARCHAR(500) NULL,
  before_value VARCHAR(1000000) NULL,
  after_value VARCHAR(1000000) NULL,
  request_id VARCHAR(64) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  CONSTRAINT fk_audit_operator FOREIGN KEY (operator_id) REFERENCES profile(id)
);

CREATE TABLE IF NOT EXISTS vector_sync_task (
  id BIGINT NOT NULL,
  resume_id BIGINT NOT NULL,
  resume_version INT NOT NULL,
  operation ENUM('UPSERT','DELETE') NOT NULL,
  status ENUM('PENDING','PROCESSING','SUCCESS','FAILED') NOT NULL DEFAULT 'PENDING',
  payload VARCHAR(1000000) NULL,
  attempts INT NOT NULL DEFAULT 0,
  next_attempt_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  started_at DATETIME(3) NULL,
  completed_at DATETIME(3) NULL,
  error_message VARCHAR(1000) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  CONSTRAINT fk_vector_resume FOREIGN KEY (resume_id) REFERENCES resume(id),
  CONSTRAINT ck_vector_task CHECK (resume_version>=1 AND attempts>=0 AND (operation='DELETE' OR payload IS NOT NULL))
);

ALTER TABLE resume ADD COLUMN parsed_birth_date DATE;
ALTER TABLE resume ADD COLUMN parsed_age INT;
ALTER TABLE resume ADD COLUMN parsed_work_experience_years INT;


-- 职位向量生命周期：事务出站队列，版本快照及有限重试。
CREATE TABLE IF NOT EXISTS job_vector_task (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,
 job_id BIGINT NOT NULL,
 job_version INT NOT NULL,
 operation VARCHAR(10) NOT NULL,
 status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
 payload LONGTEXT NULL,
 attempts INT NOT NULL DEFAULT 0,
 next_attempt_at DATETIME(3) NOT NULL,
 started_at DATETIME(3) NULL,
 completed_at DATETIME(3) NULL,
 error_message VARCHAR(1000) NULL,
 created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 KEY idx_job_vector_pending(status,next_attempt_at),
 KEY idx_job_vector_order(job_id,id),
 CONSTRAINT fk_job_vector_job FOREIGN KEY (job_id) REFERENCES job(id)
);
